
services:
  backend:
    image: visvirideveloper/rentcar-back:latest
    container_name: rentcar-backend
    ports:
      - "8080:8080"
    restart: always
  database:
    image: mysql:8.0
    container_name: rentcar-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: always